DEFINE SCHEMA {{ sf_db }}.RAW;

DEFINE SCHEMA {{ sf_db }}.TRANSFORM;

DEFINE SCHEMA {{ sf_db }}.REPORTING;

DEFINE TABLE {{ sf_db }}.RAW.SF_ACCOUNTS (
    ACCOUNT_ID VARCHAR NOT NULL,
    ACCOUNT_NAME VARCHAR,
    INDUSTRY VARCHAR,
    ANNUAL_REVENUE NUMBER(18,2),
    CREATED_DATE TIMESTAMP_NTZ,
    LAST_MODIFIED_DATE TIMESTAMP_NTZ,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DEFINE TABLE {{ sf_db }}.RAW.SF_OPPORTUNITIES (
    OPPORTUNITY_ID VARCHAR NOT NULL,
    ACCOUNT_ID VARCHAR,
    OPPORTUNITY_NAME VARCHAR,
    STAGE_NAME VARCHAR,
    AMOUNT NUMBER(18,2),
    CLOSE_DATE DATE,
    CREATED_DATE TIMESTAMP_NTZ,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DEFINE TABLE {{ sf_db }}.TRANSFORM.SF_ACCOUNTS_CLEAN (
    ACCOUNT_ID VARCHAR NOT NULL,
    ACCOUNT_NAME VARCHAR,
    INDUSTRY VARCHAR,
    ANNUAL_REVENUE NUMBER(18,2),
    CREATED_DATE TIMESTAMP_NTZ,
    LAST_MODIFIED_DATE TIMESTAMP_NTZ,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _TRANSFORMED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DEFINE TABLE {{ sf_db }}.TRANSFORM.SF_OPPORTUNITIES_CLEAN (
    OPPORTUNITY_ID VARCHAR NOT NULL,
    ACCOUNT_ID VARCHAR,
    OPPORTUNITY_NAME VARCHAR,
    STAGE_NAME VARCHAR,
    AMOUNT NUMBER(18,2),
    CLOSE_DATE DATE,
    CREATED_DATE TIMESTAMP_NTZ,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _TRANSFORMED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DEFINE TABLE {{ sf_db }}.REPORTING.RPT_PIPELINE_SUMMARY (
    ACCOUNT_ID VARCHAR,
    ACCOUNT_NAME VARCHAR,
    INDUSTRY VARCHAR,
    TOTAL_OPPORTUNITIES NUMBER,
    TOTAL_PIPELINE_VALUE NUMBER(18,2),
    AVG_DEAL_SIZE NUMBER(18,2),
    _REPORT_GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DEFINE TABLE {{ sf_db }}.REPORTING.RPT_ACCOUNT_OVERVIEW (
    ACCOUNT_ID VARCHAR,
    ACCOUNT_NAME VARCHAR,
    INDUSTRY VARCHAR,
    ANNUAL_REVENUE NUMBER(18,2),
    OPEN_OPPORTUNITIES NUMBER,
    WON_OPPORTUNITIES NUMBER,
    TOTAL_WON_AMOUNT NUMBER(18,2),
    _REPORT_GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DEFINE TABLE {{ sf_db }}.RAW.SF_CONTACTS (
    CONTACT_ID VARCHAR NOT NULL,
    ACCOUNT_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    CREATED_DATE TIMESTAMP_NTZ,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DEFINE FUNCTION {{ sf_db }}.RAW.GET_ACCOUNT_REVENUE(ACCT_ID VARCHAR)
RETURNS NUMBER(18,2)
AS
$$
  SELECT COALESCE(ANNUAL_REVENUE, 0)
  FROM {{ sf_db }}.RAW.SF_ACCOUNTS
  WHERE ACCOUNT_ID = ACCT_ID
  LIMIT 1
$$;

DEFINE FUNCTION {{ sf_db }}.RAW.MASK_EMAIL(EMAIL_VAL VARCHAR)
RETURNS VARCHAR
AS
$$
  SELECT CASE
    WHEN EMAIL_VAL IS NULL OR POSITION('@' IN EMAIL_VAL) = 0 THEN EMAIL_VAL
    ELSE LEFT(EMAIL_VAL, 1)
         || REPEAT('*', POSITION('@' IN EMAIL_VAL) - 3)
         || SUBSTR(EMAIL_VAL, POSITION('@' IN EMAIL_VAL) - 1)
  END
$$;

